name: Cypress Cucumber CI
on: [push,workflow_dispatch]
jobs:
 cypress-Cucumber-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests run
        run: |
          npm i 
          npm run test:all
          
      - name: Generate report
        if: always()
        run: npm run report

      - name: Publish artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: tests-report
          path: cypress/reports/
